# CI - CD file for the Sorting application
language: node_js

os: linux
dist: trusty

# make use of the latest version of NodeJS
node_js:
  - node

# Specifying the branched to be ran on
branches:
  only:
    - master
    - develop
  except:
    - experimental

# Cache
cache:
  npm

# installing the firebase tools necessary for deployment & prepare the coverage report
before_script:
  - npm install firebase-tools -g
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

# Actual script
script:
  - npm test

after_success:
  - java -jar codacy-coverage-reporter-assembly.jar report -r coverage/lcov.info

# Deployment to Firebase
deploy:
  provider: firebase
  project: "sorting-application"
  token:
    secure: "nMTT+jNOpkymkBcAnxCccLeZ0IQB/IoA+6fyjfM7pZWC0MsNEreUVT6Vl7+FAv4CDy54Wo115MFRfrblnRpk+E/UztUqXwihihOYqOx02a7HKjkCpHIR/d93RKlYY/K3OEyXtdKba7HHnTZO4ejCZNd1zrUPS5c0QpSAEURScXldW3dVw2HLeXmdPlI0uhTM8bBsyPnCtUkEUgIzaqo873QgchgyVZcygK6P2jTn7Yjac7/fkjNZbevXFfMDqaTu3UVMELeI8bgVTWFhZCRvQXBtvweDG72wOuTvuLCTggfdani3sld7IHYiLBrGuDZ+6ZIJTti6skN33LtSHs+VSAUQjuGeNuLuYR+nDZYtuhKAsLubST7Mm9YsZF5kKxOsZu24anfWf1WhuFoYlKlQxJN32R0bCWVODQDZSx19V7sWKj4aWodjGaoKe5vvAvMBnhF/ysMr0t9HLTxqJ0MomP5ZxYsZJXVa7dzrv1rZKz1aKeZETU+d9pqNvH/LoqIXc3y5xxJt1ucz14cNgBg8B9ntdYEIIqotKHkmT3BVCMoxG9VVqjiFbJJVQREHEiyjiFY1hMt0ss90Mz68tVB4gje2iECGTArcmNwmciZiQj2IS8XPuNTobIe3eZrsFxzW0hN2DsoXU7gMKDuys+Y/x0v/O8Wc7MTpLi6v7Ai/Q7s="
  message: "Deployment to firebase with Travis Build ${TRAVIS_BUILD_NUMBER}"
  on:
    branch: master