name: Sorting

on:
  push:
    branches: 
     - master
     - develop
  pull_request:
    branches: 
    - master 
    - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build-prod
      
      - name: Create test coverage
        run: jest --collectCoverage
        
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
          
      - name: codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }} 
      
  deploy:
    name: Deploy
    needs: build
    if: (github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
